### ISSUE TITLE
FR - add `commit` field for inputs

### ISSUE THREAD

**Issue by thezackm** [newrelic/deployment-marker-action#25]
The new GraphQL API includes a [commit field as an optional attribute](https://docs.newrelic.com/docs/change-tracking/change-tracking-graphql/#optional-fields) to be sent on mutations. The intention of this field is to hold the Commit SHA for a marker. 

This FR is to request support for this field as an input using the default `GITHUB_SHA` variable:

```yaml
jobs:
  newrelic:
    runs-on: ubuntu-latest
    steps:
      - name: Change Tracking Marker
        uses: newrelic/deployment-marker-action@v2.0.0
        with:
          commit: "${{ github.sha }}"
          ...
```
