### ISSUE TITLE
Action fails but is marked as success

### ISSUE THREAD

**Issue by edisonspencer** [newrelic/deployment-marker-action#40]
If the credentials are wrong, the GitHub Action shows an error on the logs but the job status is still displayed as successful. The job should instead be marked as a failure so it would be easier to fix the credentials and re-run just the failed jobs instead of the whole flow.

> Workflow usage:
```
jobs:
  # ...
  deployment-marker:
    name: Create deployment marker
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve release version
        run:
          echo "RELEASE_VERSION=$(echo ${{ github.event.ref }} | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+$')" >> $GITHUB_ENV

      - name: Create deployment marker on New Relic
        uses: newrelic/deployment-marker-action@v2.3.0
        with:
          guid: ${{ secrets.PRODUCTION_NEW_RELIC_GUID }}
          apiKey: ${{ secrets.PRODUCTION_NEW_RELIC_API_KEY }}
          region: "EU"
          version: "${{ env.RELEASE_VERSION }}"
          user: "${{ github.actor }}"
```

Example when wrong credentials are provided:

> Log shown
```
level=fatal msg="Argument \"deployment\" has invalid value $deployment.\nIn field \"entityGuid\": Expected type \"EntityGuid!\", found \"***\"."
```

> Job status returned
```
SUCCESS ✅
```

> Job status expected
```
FAILURE ❌
```
