### ISSUE TITLE
Fatal error: Timestamp cannot be more than 24 hours in past or future

### ISSUE THREAD

**Issue by leetrout** [newrelic/deployment-marker-action#76]
We are on the version 2.5.1 of the action and it just failed in our pipeline:

```
level=fatal msg="timestamp can not be more than 24 hours in the past or future. Make sure to use epoch milliseconds for timestamp."
```

And our config:

```
          - name: New Relic Application Deployment Marker
            uses: newrelic/deployment-marker-action@afc78909100f9f795c2aadd6967254344bcb66bf # v2.5.1
            with:
                apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
                guid: ${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID }}
                version: ${{ github.sha }}
                user: ${{ github.actor }}
```
